---
- name: Check if mount point exists
  ansible.builtin.stat:
    path: "{{ item.path }}"
  register: results

- name: Ensure mount point folder exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not results.stat.exists

- name: Ensure filesystem are mounted
  ansible.posix.mount:
    backup: "{{ item.backup | default(omit) }}"
    boot: "{{ item.boot | default(omit) }}"
    fstab: "{{ item.fstab | default(omit) }}"
    fstype: "{{ item.fstype | default(omit) }}"
    opts: "{{ item.opts | default(omit) }}"
    path: "{{ item.path }}"
    src: "{{ item.src | default(omit) }}"
    state: "{{ item.state }}"
